name: "CD - Deploy to Production"

on:
  push:
    branches: [ main ]

jobs:
  deploy-prod:
    name: "Deploy Bundle to Production"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Databricks CLI
        uses: databricks/setup-cli@v0.2

      - name: Deploy DAB to Production
        env:
          DATABRICKS_HOST: ${{ secrets.DATABRICKS_HOST }}
          DATABRICKS_CLIENT_ID: ${{ secrets.DATABRICKS_CLIENT_ID }}
          DATABRICKS_CLIENT_SECRET: ${{ secrets.DATABRICKS_CLIENT_SECRET }}
        run: |
          echo "🚀 Deploying to Production environment..."
          databricks bundle deploy -t prod
